version: 2

project_name: ccode

builds:
  - id: ccode
    main: ./
    binary: ccode
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: ccode
    ids:
      - ccode
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  prerelease: auto

changelog:
  use: github
  sort: desc
